// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationTest.Models;

namespace MigrationTest.Migrations
{
    [DbContext(typeof(MsvApprovalContext))]
    partial class MsvApprovalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Migration.Models.AdmissionDetails", b =>
                {
                    b.Property<DateTime?>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdmissionTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionTypeCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionTypeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionTypeNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmbulatoryCareInformationID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicalComplexityID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncounterTypeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedLengthOfStay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedLengthOfStayUnitCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedLengthOfStayUnitCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedLengthOfStayUnitID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedLengthOfStayUnitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedLengthOfStayUnitNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtendedWaitPatientID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalCauseID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScheduledAdmissionDate")
                        .HasColumnType("datetime2");

                    b.ToTable("AdmissionDetails");
                });

            modelBuilder.Entity("Migration.Models.ApprovalCancellationRemarks", b =>
                {
                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarkDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarkDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarkSection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarkTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarkType")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ApprovalCancellationRemarks");
                });

            modelBuilder.Entity("Migration.Models.ApprovalException", b =>
                {
                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ApprovalException");
                });

            modelBuilder.Entity("Migration.Models.ApprovalReferralRemarks", b =>
                {
                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarkDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarkDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarkSection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarkTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarkType")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ApprovalReferralRemarks");
                });

            modelBuilder.Entity("Migration.Models.Attachments", b =>
                {
                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentBinary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("RelatedToApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RelatedToTransactionRequestDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RelatedToTransactionTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedToTransactionTypeCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedToTransactionTypeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedToTransactionTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedToTransactionTypeNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Migration.Models.BeneficiaryDetails", b =>
                {
                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AgeUnitID")
                        .HasColumnType("int");

                    b.Property<string>("AgeUnitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenderID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("IdentityTypeID")
                        .HasColumnType("tinyint");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipBeneficiaryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MembershipEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MembershipInceptionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MembershipMRN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipMemberClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipPlanType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipPolicyHolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipPolicyNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NationalityID")
                        .HasColumnType("int");

                    b.Property<string>("NationalityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("BeneficiaryDetails");
                });

            modelBuilder.Entity("Migration.Models.Diagnosis", b =>
                {
                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DRGCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DRGName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DiagnosisDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosisDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisOnSetFlagCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisOnSetFlagID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisOnSetFlagName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisTypeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUnacceptPrimaryDiagnosis")
                        .HasColumnType("bit");

                    b.Property<string>("MDBID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDBName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDCID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDCName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Diagnosis");
                });

            modelBuilder.Entity("Migration.Models.DischargeDetails", b =>
                {
                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DischargeModeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DischargeTime")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DischargeDetails");
                });

            modelBuilder.Entity("Migration.Models.Editing", b =>
                {
                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CanCancel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CanFollowUp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.ToTable("Editing");
                });

            modelBuilder.Entity("Migration.Models.Header", b =>
                {
                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ApprovalInquiryAllow")
                        .HasColumnType("bit");

                    b.Property<string>("ApprovalProcessorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalTypeCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalTypeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalTypeNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChannelID")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FollowUpNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFromReferal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInPatient")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMSVPSVRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsParent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("MsvPsvID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentApprovalID")
                        .HasColumnType("bigint");

                    b.Property<int>("PayerID")
                        .HasColumnType("int");

                    b.Property<bool>("PayerIsTPA")
                        .HasColumnType("bit");

                    b.Property<string>("PayerLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicianCategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicianCategoryCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicianCategoryID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicianCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicianCategoryNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicianID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicianName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicianSCFHS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProviderCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ProviderCodePayer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProviderID")
                        .HasColumnType("int");

                    b.Property<string>("ProviderLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferalNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialityCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialityID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialityNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSpecialityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSpecialityCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSpecialityID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSpecialityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSpecialityNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TPAIsTPA")
                        .HasColumnType("bit");

                    b.Property<int>("TPAPayerID")
                        .HasColumnType("int");

                    b.Property<string>("TPAPayerLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TPAPayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TransactionRequestDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionTypeCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionTypeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionTypeNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UILayout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitTypeCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitTypeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitTypeNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Headers");
                });

            modelBuilder.Entity("Migration.Models.HealthyLifeStyleDetails", b =>
                {
                    b.Property<string>("AllergyHistoryID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCommencement")
                        .HasColumnType("datetime2");

                    b.Property<string>("DietTypeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EposideOfTreatmentID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationOfImairmentID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PastMedicalHistoryID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicalActivityID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmokingConsumptionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportTypeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstanceAbuseHistoryID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TabacoSmokingStatusID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeOfCommencement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VascularProcedureID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referalOfAbuseID")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("HealthyLifeStyleDetails");
                });

            modelBuilder.Entity("Migration.Models.HospitalCareDetails", b =>
                {
                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedLengthOfStay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedStayLenthInDays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntendedStayLengthID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterhospitalContractedPatientID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOLeavePeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationTreatmentTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientDays")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("HospitalCareDetails");
                });

            modelBuilder.Entity("Migration.Models.IllnessTypes", b =>
                {
                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Checked")
                        .HasColumnType("bit");

                    b.Property<string>("How")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IllnessTypeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IllnessTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("When")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Where")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("IllnessTypes");
                });

            modelBuilder.Entity("Migration.Models.MSV.BeneficiaryDetails", b =>
                {
                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("IdentityTypeID")
                        .HasColumnType("tinyint");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MembershipEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MembershipInceptionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MembershipMemberClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipPlanType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipPolicyHolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipPolicyNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MsvPsvID")
                        .HasColumnType("int");

                    b.Property<string>("NationalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NationalityID")
                        .HasColumnType("int");

                    b.Property<string>("NationalityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("MSVBeneficiaryDetails");
                });

            modelBuilder.Entity("Migration.Models.MSV.Header", b =>
                {
                    b.Property<string>("BenfitTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BenfitTypeCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BenfitTypeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BenfitTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BenfitTypeNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChannelID")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MSVExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MsvPsvID")
                        .HasColumnType("int");

                    b.Property<int>("MsvTypeID")
                        .HasColumnType("int");

                    b.Property<string>("MsvTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PayerID")
                        .HasColumnType("int");

                    b.Property<bool>("PayerIsTPA")
                        .HasColumnType("bit");

                    b.Property<string>("PayerLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProviderCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ProviderCodePayer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProviderID")
                        .HasColumnType("int");

                    b.Property<string>("ProviderLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialityCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialityID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialityNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSpecialityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSpecialityCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSpecialityID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSpecialityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSpecialityNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TPAIsTPA")
                        .HasColumnType("bit");

                    b.Property<int>("TPAPayerID")
                        .HasColumnType("int");

                    b.Property<string>("TPAPayerLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TPAPayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TransactionRequestDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("MSVHeader");
                });

            modelBuilder.Entity("Migration.Models.MSV.PayerResponse", b =>
                {
                    b.Property<int>("MsvPsvID")
                        .HasColumnType("int");

                    b.Property<string>("MsvPsvStatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MsvPsvStatusCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MsvPsvStatusID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MsvPsvStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MsvPsvStatusNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayerReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarkCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarkCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarkID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarkName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarkNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResponseDateTime")
                        .HasColumnType("datetime2");

                    b.ToTable("MSVPayerResponse");
                });

            modelBuilder.Entity("Migration.Models.MSV.TableOfBenefit", b =>
                {
                    b.Property<string>("Copayment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deductible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeductibleTobeCollected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MPNDeductible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxPhysicianFee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MsvPsvID")
                        .HasColumnType("int");

                    b.Property<string>("OCNDeductible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OHNDeductible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreAuthorizationLimit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduleOfBenefit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatmentExpenses")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("TableOfBenefit");
                });

            modelBuilder.Entity("Migration.Models.PayerComment", b =>
                {
                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommentText")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("PayerComment");
                });

            modelBuilder.Entity("Migration.Models.PayerResponse", b =>
                {
                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalStatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalStatusCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalStatusID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalStatusNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalValidityPeriodDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalValidityPeriodUnitCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedLengthOfStaySummaryDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedLengthOfStaySummaryUnitCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayerReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemarkCommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RemarkCommentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResponseDateTime")
                        .HasColumnType("datetime2");

                    b.ToTable("PayerResponse");
                });

            modelBuilder.Entity("Migration.Models.ServiceItem", b =>
                {
                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ApprovedCostAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PayerServiceCommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayerServiceCommentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedToApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedToTransactionTypeCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedToTransactionTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedToTransactionTypeNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceDecisionsApprovedCostCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ServiceDecisionsApprovedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceStatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceStatusCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceStatusID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceStatusNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ServiceItem");
                });

            modelBuilder.Entity("Migration.Models.Services", b =>
                {
                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralModeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralModeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralModeOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralReasonID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralReasonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalApprovedCostAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TotalApprovedCostCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalRequestedCostAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TotalRequestedCostCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Migration.Models.TransactionMappingList", b =>
                {
                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpiresIn")
                        .HasColumnType("int");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<int>("TransactionTypeID")
                        .HasColumnType("int");

                    b.Property<string>("TransactionTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("TransactionMappingList");
                });

            modelBuilder.Entity("Migration.Models.TriageAssesments", b =>
                {
                    b.Property<string>("ApprovalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChiefComplaint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignContactLenseID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignContactLenseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignLeftEYEAddDistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignLeftEYEAddNear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignLeftEYEAxisDistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignLeftEYEAxisNear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignLeftEYEBiofacl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignLeftEYECYLDistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignLeftEYECYLNear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignLeftEYEPDDistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignLeftEYEPDNear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignLeftEYEPrismDistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignLeftEYEPrismNear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignLeftEYESPHDistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignLeftEYESPHNear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignLeftEYEVertext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignPhysicianLicenseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignPhysicianName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpticalVitalSignPrescriptionTestID")
                        .HasColumnType("int");

                    b.Property<string>("OpticalVitalSignPrescriptionTestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpticalVitalSignProviderID")
                        .HasColumnType("int");

                    b.Property<string>("OpticalVitalSignProviderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignRegularLenseID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignRegularLenseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignRightEyeAddDistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignRightEyeAddNear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignRightEyeAxisDistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignRightEyeAxisNear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignRightEyeBiofacl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignRightEyeCYLDistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignRightEyeCYLNear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignRightEyePDDistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignRightEyePDNear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignRightEyePrismDistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignRightEyePrismNear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignRightEyeSPHDistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignRightEyeSPHNear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignRightEyeVertext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignVisitPurposeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpticalVitalSignVisitPurposeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignificantSigns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriageCategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriageCategoryCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriageCategoryID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriageCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriageCategoryNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TriageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TriageTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignArrivalMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignDeliveryTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignDeliveryTypeCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignDeliveryTypeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignDeliveryTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignDeliveryTypeNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignDiastolicBloodPressure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignDispositionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignHeartRhythmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignHeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignIllnessDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignIllnessDurationUnitCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignIllnessUnitCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignIllnessUnitCodeParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignIllnessUnitID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignIllnessUnitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignIllnessUnitNameParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VitalSignLMPDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VitalSignLastMenstruationPeriodDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VitalSignPulse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignRespiratoryRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignSystolicBloodPressure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitalSignTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VitalSignWaitingTime")
                        .HasColumnType("int");

                    b.Property<string>("VitalSignWeight")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("TriageAssesments");
                });
#pragma warning restore 612, 618
        }
    }
}
